### ISSUE TITLE
Changing Author to Admin not always sticking

### ISSUE THREAD

**Issue by erica-sigma** [sigmacomputing/intercom_issues#18]
> When I try to make 2 of our users admins...it automatically switches them back to author when i refresh my screen.

Note: @mhseiden saw this behavior internally the other day. When going back the next day, there was no issue. 
When I tried to reproduce in a test instance, I had no issue when I swapped someone from Admin to Author and then back again. When I tried to change someone who was always an author to an admin, I saw the issue. 

***Steps to Reproduce***
1. Go to settings. 
2. Change and Author to and Admin.
3. Refresh the page. 

**Link:** [Conversation with Art Malanok](https://app.intercom.com/a/apps/gu1e0q0t/respond/inbox/all/conversations/23136057023)

**Customer:** [Art Malanok](https://app.intercom.com/a/apps/gu1e0q0t/users/5d0ba59a8b3c04554db38313/all-conversations) from [Seattle Genetics](https://app.intercom.com/a/apps/gu1e0q0t/companies/5d0c1942373542fd19bd2507)
**Customer ID:** xHqSJokpq3R2jvvOoUKxy801pT7R8
**Company ID:** 245d693b-6848-43e6-b76f-989f1f8f61cb

___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/gu1e0q0t/respond/inbox/all/conversations/23136057023) when this issue is closed.

**Comment by jfranty** [comment]
This should be fixed now. We rolled out a change to the frontend before deploying a necessary backend change.
